### ISSUE TITLE
null value error in routes/index.js

### ISSUE THREAD

**Issue by gcoskun** [vocol/vocol#109]
line 93 in routes/index.js causes a nullpoint for me. 
data.results.bindings needs to be checked for null

...
        silent: false
      }).stdout;
      if (output) {
        client.query(qOnt, function(error, data) { // query on dataset.
          if (error) {
            console.log(error);
          }
          var result = data.results.bindings;
          if (result[0] != null) {
            // json values of the query result
          .....

**Comment by ahemaid** [comment]
This was in the old version, I think you will not see this error again. I will close the ticket
