### ISSUE TITLE
TurtleEditor is not available

### ISSUE THREAD

**Issue by javadch** [vocol/vocol#111]
The TurtleEditor package as mentioned in the "Required Packages and tools" points to the [TurtleEditor](https://github.com/vocol/vocol/tree/master/TurtleEditor) folder on the master branch, but it is not available there!

Also, there is no installation instruction neither for Windows nor for Linux.

**Comment by lavdim** [comment]
Hi, 

the Turtle Editor is completely integrated now and located here: https://github.com/vocol/vocol/tree/master/views/editor, so there is no need for a separate installation, as with many other tools.

In the following Wiki, there are installation instructions: https://github.com/vocol/vocol/wiki/Installation-and-Configuration .

In addition you can install VoCol using the following docker image: https://hub.docker.com/r/ahemid/newvocol/ 

Should you have additional questions/issues, please do not hesitate to contact us.

**Comment by javadch** [comment]
Thanks for the information. I would suggest fixing the step in the "Required Packages and tools" that requests installing TurtleEditor.

**Comment by ahemaid** [comment]
@javadch, thanks for your recommendation. 
"Required Packages and tools" was updated to separate between tools needs to be installed and those which are already integrated.
