### ISSUE TITLE
Dockerfile is not available

### ISSUE THREAD

**Issue by javadch** [vocol/vocol#112]
I need to customize this [docker image](https://hub.docker.com/r/ahemid/newvocol) by adding non-root users, volumes, auto startup services, etc. Could you please add the docker file to the repository. Usually, Github projects have a `docker` folder that contains the `Dockerfile`. The Dockergub then can be set to automatically pull this file and build a new image when changes are committed to the repository.
In this case, it would easy for me to fork from your Github repo and further develop/customize it.

**Comment by ahemaid** [comment]
Hi @javadch, 
Yes, you are right in regards to have a docker file to build the docker image. 
We have taken your suggestion in our consideration and we have created the docker file to build Vocol. 
it is now included in the repository.

**Comment by javadch** [comment]
Thanks @ahemaid 👍
