### ISSUE TITLE
git pull within docker causes following error

### ISSUE THREAD

**Issue by gcoskun** [vocol/vocol#113]
Hi, I am using the docker image. Within the docker container I did a git pull. When I try to start vocol I get the following output:
> vocol@0.0.1 start /home/project/vocol
> node ./bin/www "80" "3030"

VoCol server is running on port 80
Jena Fuseki server is running on port 3030
GET // 200 14.693 ms - 22798
GET //javascripts/bower_components/bootstrap/dist/css/bootstrap.css 200 7.190 ms - 146010
GET //javascripts/bower_components/bootstrap/dist/js/bootstrap.min.js 200 6.076 ms - 37045
GET //javascripts/bower_components/jquery/dist/jquery.min.js 200 6.981 ms - 86659
GET //javascripts/bower_components/bootstrap/dist/css/bootstrap.min.css 200 6.264 ms - 121200
GET //javascripts/crypto-js/crypto-js.js 200 6.785 ms - 191936
GET //semantic/dist/semantic.min.js 200 6.774 ms - 282771
GET //ckeditor/ckeditor.js 200 7.271 ms - 560314
GET //javascripts/bower_components/bootstrap/dist/css/bootstrap-theme.min.css 200 0.482 ms - 23409
GET //semantic/dist/semantic.min.css 200 0.462 ms - 593653
GET //stylesheets/style.css 200 0.409 ms - 2986
GET //semantic/dist/themes/default/assets/fonts/icons.woff2 200 1.395 ms - 77160
GET //ckeditor/config.js?t=H8DA 200 0.781 ms - 1412
GET //ckeditor/lang/en.js?t=H8DA 200 1.684 ms - 11046
GET //ckeditor/skins/kama/editor.css?t=H8DA 200 1.646 ms - 25835
GET //ckeditor/styles.js?t=H8DA 200 0.784 ms - 5546
GET //ckeditor/plugins/confighelper/plugin.js?t=H8DA 200 0.772 ms - 10112
GET //ckeditor/plugins/scayt/dialogs/dialog.css 200 0.803 ms - 419
GET //ckeditor/plugins/tableselection/styles/tableselection.css 200 0.442 ms - 1082
GET //ckeditor/skins/kama/icons.png?t=dee99e2 200 0.842 ms - 6196
GET //ckeditor/contents.css?t=H8DA 200 0.865 ms - 2955
GET //ckeditor/plugins/tableselection/styles/tableselection.css 200 0.774 ms - 1082
GET //ckeditor/contents.css?t=H8DA 200 0.744 ms - 2955
GET //ckeditor/plugins/tableselection/styles/tableselection.css 200 0.807 ms - 1082
POST //config 200 20.476 ms - 1495
node: symbol lookup error: /home/project/vocol/node_modules/bcrypt/lib/binding/bcrypt_lib.node: undefined symbol: _ZN4node19GesfdsfsdCurrentEvenfdsfddsfdtLoopEPN2v87IsolateE
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! vocol@0.0.1 start: `node ./bin/www "80" "3030"`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the vocol@0.0.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-01-30T15_23_43_093Z-debug.log

**Comment by ahemaid** [comment]
I have seen this error before I have updated it on the new version of Vocol. It is related to changes of bcrypt lib. The workaround this issue to update package.json bcrypt version from 

> 3.0.0 

to 

> 3.0.1

**Comment by gcoskun** [comment]
the package.json file contains already 3.0.1

**Comment by ahemaid** [comment]
yesterday, I have the same issue, I was able to get rid of out by update **nodejs** and **npm** frameworks to the last version. I will update the docker image with the last versions of  **noderjs** and **npm**

**Comment by ahemaid** [comment]
I handle this in the new vocol version. I also have updated the docker image so please update us if you still have a problem.
