### ISSUE TITLE
routes/index.js

### ISSUE THREAD

**Issue by gcoskun** [vocol/vocol#115]
I propose to add two line here as shown below line 93 and 99, because sometimes "data" is null in my case and it causes errors

file routes/index.js

 84       // check if fuseki endpoint is running
 85       var output = shell.exec('fuser -v -n tcp ' + endpointPortNumber.toString(), {
 86         silent: false
 87       }).stdout;
 88       if (output) {
 89         client.query(qOnt, function(error, data) { // query on dataset.
 90           if (error) {
 91             console.log(error);
 92           }
 **93          if (data) {**
 94           var result = data.results.bindings;
 95           if (result[0] != null) {
 96             // json values of the query result
 97             metaData = result;
 98           }
 **99         }**
100           client.query(qe, function(error, data) { // query on dataset.
101             if (error) {
102               console.log(error);
103             }
104             if (data) {
105               // string to hold table content
106               statistics = "";

**Comment by ahemaid** [comment]
I handle this in the new vocol version. I also have updated the docker image so please update us if you still have a problem.
