### ISSUE TITLE
URLs to non-existing sub pages return a blank page and status code 200

### ISSUE THREAD

**Issue by sebbader** [vocol/vocol#118]
Meaningless paths do not lead to a 404. For instance, https://vocol.iais.fraunhofer.de/sto/queryingasd leads to a blank website, while only https://vocol.iais.fraunhofer.de/sto/querying actually exists. This is a minor issue for sure, just wanted to let you know.

**Comment by ahemaid** [comment]
We are trying to restrict our site to the routes which we have. So other routes are not accepted. This is our concern right now.

**Comment by ahemaid** [comment]
This is related to the route path and since it is misspelled, it will show an error. Currently, we will not take any further step for this.

**Comment by lavdim** [comment]
I think it would be good to show a message that this page doesn't exist.
