### ISSUE TITLE
Notify vocabulary engineers of errors

### ISSUE THREAD

**Issue by clange** [vocol/vocol#31]
To make more precise what we wrote in the paper: I think there is an easy way of assigning vocabulary engineers to all generated validation issues. We could assume that a team `vocabulary_engineers` has been set up in the repository, and determine all users in this team. Thus, issues would be Cced to _all_ vocabulary engineers. (I don't see an easy way of notifying _the_ single vocabulary engineer who should be “in charge” of a specific issue.)

**Comment by np00** [comment]
For now, I assign the issue to the latest person, who changed something. I can adapt it to a team, but then, one needs always to create these teams themselves before being able to use our script.

**Comment by lavdim** [comment]
Fixed.
