### ISSUE TITLE
Remove root permission when is not neccesary

### ISSUE THREAD

**Issue by lavdim** [vocol/vocol#35]
When no root permission is not necessary any more, execute the further commands as user <del>"vagrant"</del>`mobivoc`.

**Comment by clange** [comment]
I'd recommend turning the logic around: execute as much as possible as user `mobivoc` (which `root` would have to create initially), give `mobivoc` sudo permission, and then only use `sudo` when it's strictly needed.

**Comment by lavdim** [comment]
Fixed.
