### ISSUE TITLE
Script for self-service setup of VoCol on top of a GitHub repository

### ISSUE THREAD

**Issue by clange** [vocol/vocol#36]
The following tasks should be automated:
- setting up the VoCol validation and publication service as a client to the given GitHub repository
- setting up suitable teams (domain experts, knowledge engineers, …) in the organization
- setting up suitable labels (e.g. validation error) in the issue tracker
- … (@soeren1611, @np00, @lavdim, please add more here)

**Comment by lavdim** [comment]
Realized in different way.
