### ISSUE TITLE
Serve vocabulary through a SPARQL endpoint (proxied through Apache)

### ISSUE THREAD

**Issue by clange** [vocol/vocol#38]
… and wrap the SPARQL endpoint into port 80 by using some kind of an Apache proxy configuration (because other ports will not necessarily be open on the server that runs VoCol, for security reasons).

Here's how this proxy configuration works: http://stackoverflow.com/questions/7529324/how-to-rewrite-proxy-an-apache-uri-to-an-application-listening-on-a-specific-p. The same pattern will be applicable to making Google App Engine (for schemaorg) on port 8080 publicly available through port 80.

**Comment by lavdim** [comment]
Part of making Google App Engine available through port 80 - finished

**Comment by clange** [comment]
I.e. now also Fuseki works through the proxy? Please let me know how; today in the afternoon I can configure the demo server accordingly.

**Comment by lavdim** [comment]
Fixed.
