### ISSUE TITLE
Use stow package manager for installations w/o a package manager

### ISSUE THREAD

**Issue by clange** [vocol/vocol#43]
We are aiming at installing most packages using the system's package manager (e.g. apt-get on Ubuntu, zypper on SUSE, etc.), as this is the cleanest way. It permits uninstallation and easy updates and therefore helps to maintain a VoCol installation over a long time.

(BTW if PyGithub is available through apt-get on Ubuntu – on SUSE it is! – we should install it using apt-get rather than pip. pip permits uninstallation but is, of course, not integrated with the system-wide update manager.)

Raptor remains [to be installed manually](https://github.com/mobivoc/vocol/blob/56913ecb5cfebd5672878bd3242574b33a3d5b66/Vagrant/BoxFiles/bootstrap.sh#L31). To make it uninstallable, we can use [stow](http://www.gnu.org/software/stow/), a poor man's package manager. stow will have to be installed using `configure && make && make install`, but from that point onwards one can change the following lines

```
tar -zxvf raptor2-2.0.15.tar.gz
cd raptor2-2.0.15
./configure # no sudo required here, only required for "make install"
make
sudo make install
```

to …

```
# as user mobivoc:

tar -zxvf raptor2-2.0.15.tar.gz
cd raptor2-2.0.15
./configure --prefix /usr/local/stow/$(basename $PWD)
make
sudo make install # BTW everything except this command should be executed as non-root, e.g. as user "mobivoc"
(cd /usr/local/stow/$(basename $PWD); sudo stow -v .)
```

FYI the `$(basename $PWD)` construction is not strictly _necessary_, but please enter `basename $PWD` once to understand how it works :-)

`make install` now installs stuff into /usr/local/stow/packagename.  In the latter directory, `stow .` creates symlinks such as `/usr/local/bin/program -> /usr/local/stow/packagename/bin/program`, whereas `stow -D .` "uninstalls" the package by removing these symlinks.

**Comment by lavdim** [comment]
Fixed.
