### ISSUE TITLE
Prevent race conditions: record IDs of all commits that have been processed already

### ISSUE THREAD

**Issue by clange** [vocol/vocol#45]
vocolJob.sh currently calls issueGenerator.py and vocabularyGenerator.py with an INTERVAL of 5 minutes. vocolJob.sh itself is run by cron every 5 minutes. Thus it's theoretically possible that we lose some commits. vocolJob.sh should therefore consider _more_ commits than just those of the past 5 minutes. To prevent double processing of a commit, it should record all commits it has processed already.

**Comment by clange** [comment]
What's even more elegant is a solution via hooks, i.e. event triggers run from GitHub's side (#30).

**Comment by lavdim** [comment]
Fixed.
