### ISSUE TITLE
Restructuring: Creating an own repository for VoCol and the other planned initiatives.

### ISSUE THREAD

**Issue by np00** [vocol/vocol#50]

**Comment by clange** [comment]
Not sure what this means – VoCol already has a repository of its own. Or do you mean a GitHub _organization_ of its own? This is possible. One could then even move the mobivoc/vocol repository to new_organization/vocol. But this will break the old repository URL, so let's not do it while our paper is still under review.

**Comment by np00** [comment]
The problem is: I do not want to set up the two others repos as part of the mobivoc project. I would propose to create a new organization with the two new inivatives (lucid, shopfloor) and we are going to move mobivoc to that place later.

**Comment by clange** [comment]
Yes, makes sense. So, let's have a "vocol" organization, and under that organization repositories "vocol", "mobivoc", "shopfloor", etc. But only after the ESWC notification.

**Comment by np00** [comment]
I talked also with Sören about it and he proposed the exact same thing :) I created for now the other repositories. The renaming will be done after the ESWC notification

**Comment by np00** [comment]
The organisation was now renamed.
