### ISSUE TITLE
Turtle Editing in the Browser with Syntax Checking and Highlighting

### ISSUE THREAD

**Issue by data-whisperer** [vocol/vocol#51]
Using open source libraries and some Javascript we can comfortably edit turtle files in the browser _and_ immediately check for syntax errors. A demo and more information can be found in https://github.com/mobivoc/vocol/tree/master/TurtleEditor.

Where the N3 parser used here does not suffice, or where we want to validate different syntaxes (e.g. OWL Manchester), the [PEG.js](http://pegjs.org) parser generator is an option to create custom parsers.

**Comment by np00** [comment]
This is precisely what I had in mind for the future - thanks a lot for that link!

**Comment by clange** [comment]
We might be able to reuse code from [XTurtle](http://aksw.org/Projects/Xturtle.html), or at least take inspiration from it, thus closing #41

**Comment by clange** [comment]
@data-whisperer We updated some more comments and closed some old issues (#41, #37) as duplicates.
