### ISSUE TITLE
In the client-side editor, use prefix.cc to look up common prefixes

### ISSUE THREAD

**Issue by clange** [vocol/vocol#53]
http://prefix.cc/

API documentation: http://prefix.cc/about

We could do this in two directions:
- when a user starts using a prefix (e.g. typing `foaf:Person`), add prefix binding declarations (`@prefix`) automatically
- when a user types or copies/pastes full URIs, look up their common prefixes and suggest to abbreviate the URIs

[XTurtle](http://aksw.org/Projects/Xturtle.html) does this too.

**Comment by lavdim** [comment]
Integrated to some extent.
