### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by skarampatakis** [vocol/vocol#60]
Hi all, 
i have procceded with the installation instructions provided [here](https://github.com/vocol/vocol/blob/master/README.md), but i am stuck on the step where i have to make the shared url. The actual problem is that there is no `vagrant share` command as supposed to. My Vagrant version is 1.6.5. and i am installing on  `Ubuntu 15.04`. I have made an account as mentioned in [here](https://docs.vagrantup.com/v2/cli/login.html)  but there either the `vagrant login` command. Maybe there is something obvious that i am missing but I am stuck. Thank you for your time.

**Comment by lavdim** [comment]
Hi,

could you please provide more details. *Vagrant share* and *vagrant login* comes with installation of vagrant environment. In principle you have to write the *vagrant share* command into the same folder that you created for Vagrant Box, in this case VoCol Box. One problem could be the Vagrant version. VoCol is tested with the Vagrant version 1.7.4 and could be that sharing mechanism is not supported for older version. 

P.s. There are two videos in README: [VoCol Installation and Configuration](https://drive.google.com/file/d/0By1pR7FDcH8obUV6OEpxeDZ3MFk/view?pli=1) and [VoCol Usage](https://drive.google.com/file/d/0By1pR7FDcH8oTFpIRWxfUHdNS1k/view?pli=1), that explain in detail all necessary steps for installation, configuration and usage of VoCol.

Please do not hesitate to contact us for any further information.
