### ISSUE TITLE
Installation with Parallels Desktop

### ISSUE THREAD

**Issue by promania** [vocol/vocol#62]
Hello,

Could you please add a Parallels Desktop image or provide me with some additional information on how to use it with Parallels Desktop instead of VirtualBox??

Thank you in advance,
Prodromos

**Comment by lavdim** [comment]
Hi,

thanks for contacting us. We will check the possibilities of providing an image of VoCol in Parallels Desktop. Once it is done, we will let you know. However, you can find more information for installing VoCol on a clean image or server on the link https://github.com/vocol/vocol#installation-on-a-web-server.

For further information, please do not hesitate to contact us.

**Comment by lavdim** [comment]
Unfortunately, it was not possible to provide the VoCol on Parallels Destop. In addition we provide as a docker image on the following link: https://hub.docker.com/r/lavdim/vocol/.
