### ISSUE TITLE
Non-ASCII characters aren't supported

### ISSUE THREAD

**Issue by jindrichmynarz** [vocol/vocol#64]
It seems that VoCol doesn't support non-ASCII characters. See the placeholders in French or Czech labels:

<img width="461" alt="screen shot 2016-10-26 at 10 20 03" src="https://cloud.githubusercontent.com/assets/198642/19725779/dabe6488-9b87-11e6-9ada-081a901437f0.png">

**Comment by lavdim** [comment]
Fixed on vagrant version, soon will update the docker image.
