### ISSUE TITLE
Only OWL classes of properties are supported

### ISSUE THREAD

**Issue by jindrichmynarz** [vocol/vocol#65]
VoCol seems to support only instances of OWL classes for properties (e.g., `owl:ObjectProperty` or `owl:DatatypeProperty`). It ignores properties that instantiate `rdf:Property` or subclasses of OWL classes (e.g., `qb:AttributeProperty` is a subclass of `qb:ComponentProperty`, which is in turn a subclass of `owl:ObjectProperty`).

**Comment by lavdim** [comment]
Fixed in the new version.
