### ISSUE TITLE
Syntax validation starts immediately on typing

### ISSUE THREAD

**Issue by annakasprzik** [vocol/vocol#70]
Syntax validation starts immediately on typing which is a problem for very big files because the validation will also restart after each character you type. Maybe the default should be that initially, syntax validation is disabled?

**Comment by hauschke** [comment]
I support this. This would need a slightly different user interface for the syntax check in th editor. "Click to enable." should look more like something one is supposed to click: a button, or a link maybe.

**Comment by lavdim** [comment]
It has been added a possibility to disable/enable the syntax validation option.
