### ISSUE TITLE
the web is down？

### ISSUE THREAD

**Issue by Joy2233** [vocol/vocol#71]
This web is not working
 http://192.168.33.10/docs/configuration_page.html

**Comment by Joy2233** [comment]
This web is not working
http://192.168.33.10/docs/configuration_page.html

**Comment by lavdim** [comment]
This link is activated in case that you are locally running VoCol e.g. using VagrantBox.

Could you please give us more details about your use case?

If you want to install VoCol on your premises, I would suggest to use Docker Installation form as it is described in this link: https://hub.docker.com/r/lavdim/vocol/ .

**Comment by Joy2233** [comment]
Thank you for your response. Now it is working.
