### ISSUE TITLE
Automatic consistency checking.

### ISSUE THREAD

**Issue by lavdim** [vocol/vocol#74]
Add additional functionality for consistency checking during the pre-commit event and after push.

**Comment by np00** [comment]
Are you talking about the TurtleEditor or some other part?

**Comment by lavdim** [comment]
Not in this case, it should be added in the validation process before pre-commit and after push events. Rel. to the Turtle-Editor, it would be a good feature, but I think would be a bit difficult to implement.

**Comment by lavdim** [comment]
@ahemaid , is this already implemented?

**Comment by ahemaid** [comment]
Yes, Consistency checking after push has been configured. But this service needed to be selected by the admin of the instance during configuration of the repository. For 'pre-commit' is not done but it will be taken in our consideration when working on client services.
