### ISSUE TITLE
Consider adding the used Github Repository link the either to the project homepage or as a banner to the top right corner

### ISSUE THREAD

**Issue by cayjd** [vocol/vocol#76]

**Comment by cayjd** [comment]
posted by niklas

**Comment by lavdim** [comment]
Actually, adding in the homepage is left on the responsibility of the administrator of the project/ontology. This is already possible.

Adding as a banner, yes, it is on the list of our todo's but good that you point out.

**Comment by lavdim** [comment]
Done.
