### ISSUE TITLE
Turtle editor works only on Github

### ISSUE THREAD

**Issue by skarampatakis** [vocol/vocol#79]
Currently Turtle editor works on Github based repositories. Can it be more abstract so that Gitlab repos are eligible too?

**Comment by lavdim** [comment]
Yes, currently the Turtle Editor works only on Github. We will check the possibilities of making it more generic, i.e. supporting Gitlab and Bitbucket repositories.

**Comment by lavdim** [comment]
Hi @skarampatakis, thanks for asking. Actually, in the current version of the VoCol, the Gitlab is not still supported (in the previous version it was). This is in our agenda, and soon (we hope at most in two weeks) we will add this functionality. I would suggest that you skip for now testing the VoCol with Gitlab repos. 

P.s. Good idea about logs, we should store the logs and show in an appropriate way, though it is a bit tricky since many standalone tools with completely different interfaces are integrated.

**Comment by skarampatakis** [comment]
Hi @lavdim ,
any updates on this?

**Comment by lavdim** [comment]
Hi @skarampatakis, I think the GitLab and BitBucket are now supported, @ahemaid , please update on this. 
There might be still some problems bcz sometimes in the new versions of their API's, the repository hosting platform change the slightly the structure of the response after each push event sent by Web Hook on which the VoCol relies.

**Comment by skarampatakis** [comment]
I built vocol from scratch.
Enter my repo info on the config page.
The repoFolder seem to be created succesfully, it contains my repo and the files on it.
On the Vocol UI, the Editor page gives me the default repo ```testProj```. When I change the info on the form to match my repo, I get no values. It seems that it keeps requesting the github repo.

Besides of this, as you already said that the Editor may not support Gitlab repos, my repo on Gitlab is not visible anywhere. On the vizualization page I get the MobiVoc vocabulary and on Querying the same. The only thing that seems to be interacting with my repo is the Validation page, where at first it reported some errors, I fixed them and now is empty. 

Is there something that I miss?

**Comment by lavdim** [comment]
Actually the info about the Mobivoc should not be anywhere, the should be empty values. @ahemaid , please fix this.

Basically, from the steps you are describing, it seems that the VoCol is communicating with your repository, but there is something after that, which is preventing from execution of the rest of the steps.

It should be straightforward. Maybe, we can have a call next week and see what is the problem.

**Comment by ahemaid** [comment]
Hi @skarampatakis, I think such issues are not more there.
could you please try and if you still have a problem,
please open new issue, I will have a look to it 

Cherrs
