### ISSUE TITLE
SHA_NOT_FOUND

### ISSUE THREAD

**Issue by skarampatakis** [vocol/vocol#80]
I enter the info for a repo on Github on the editor page.

The connection seems to happen succesfully as the response from the github API has the filenames on my repo. 

But then I get
```
ERROR: Read from GitHub failed {message: "SHA_NOT_FOUND"}
````

**Comment by lavdim** [comment]
@ahemaid , please have a look on this.

**Comment by ahemaid** [comment]
Hi @skarampatakis,
I think this means that the authentication process with GitHub is failed. It could happen with invalid username and password. so please double check that. Moreover, the loading of files to the editor page does not mean that you have correct username and password, sometimes, I leave them empty and it will load the files from the repository.
Also, it is good to know it you are using a public or private repository. 
Thanks
