### ISSUE TITLE
Allow to empty cache manually

### ISSUE THREAD

**Issue by hauschke** [vocol/vocol#87]
When files in the repository  are exchanged (some deleted, some new) it takes some time until parts of VoCol work with the new files. Visualization worked instantly, Documentation (myvocol.org/documentation) took at least some hours, maybe even more.

**Comment by ahemaid** [comment]
Hi @hauschke, 
Normally, we are not caching since we disable the cache from the server. 
I think some framework such 'require' do the problem, so I just delete its cache everytime you reload documentation. 
so you can update you vocol with the current repo and update us
