### ISSUE TITLE
Better viewer and export for analytics

### ISSUE THREAD

**Issue by hauschke** [vocol/vocol#90]
When dealing with higher amount of classes the visualizations are unreadable. Example: Dendrogram in Firefox:
![vocol_2018-05-02 09_46_48-analytics](https://user-images.githubusercontent.com/1275231/39511477-e51ed20e-4ded-11e8-9798-e826e29cec63.png)

A zooming feature would be very useful. There is no export feature to reuse the visualizations, too.

**Comment by lavdim** [comment]
Fixed with the new DendoGram. It can be seen here: https://vocol.iais.fraunhofer.de/sto/analytics and selectiong the DendoGram option.
