### ISSUE TITLE
Large visualizations are cut off after toggling

### ISSUE THREAD

**Issue by hauschke** [vocol/vocol#91]
myvocol.org/analytics

![vocol_2018-05-02 09_46_48-analytics](https://user-images.githubusercontent.com/1275231/39511477-e51ed20e-4ded-11e8-9798-e826e29cec63.png)

The visualization is shown incompletely after hitting the toggle switch. Tested in Firefox and Chrome, latest versions.

**Comment by lavdim** [comment]
Fixed with the new DendoGram.
