### ISSUE TITLE
Zoom in evolution doesn't work

### ISSUE THREAD

**Issue by hauschke** [vocol/vocol#92]
"You can move and zoom the timeline, and select items."

How? I tried a lot of things, didn't work in latest Firefox. Additionally I would prefer if the timeline starts with something inside, for example the last 3 or 4 commits.

Maybe you can extend the documentation?

**Comment by ahemaid** [comment]
I am not sure what problem you have. but it should work. 
follows is example http://vocol.iais.fraunhofer.de/iasis/evolution
but anyhow try to update with the last version on GitHub and update us

**Comment by hauschke** [comment]
It's http://vocol.iais.fraunhofer.de/tib/, I think it was updated on Monday. How can I find out, which version it is?

**Comment by ahemaid** [comment]
I have updated  /tib with the latest version of vocol. You can give a try right now

**Comment by hauschke** [comment]
I still can't zoom in, and nothing is shown in http://vocol.iais.fraunhofer.de/tib/evolution.

**Comment by lavdim** [comment]
I think, you have to set-up a web hook (or correct the old one, IIRC there should be one) to the repository: https://github.com/annakasprzik/VoColPlayground , that points to the VoCol server. I can send you the link to your private address. Then you have to push something to the repo and the diffs will be generated and shown in the Evolution report.

**Comment by hauschke** [comment]
Works again.
