### ISSUE TITLE
Visualization doesn't work after edit

### ISSUE THREAD

**Issue by hauschke** [vocol/vocol#93]
After editing one file via VoCol the Visualization claims that "There is nothing to visualize."

http://vocol.iais.fraunhofer.de/tib/visualization

Loading files in "Edit" works, though.

**Comment by ahemaid** [comment]
Hi @hauschke 
I had a look on the error in vivo_owl.ttl file

`The previous short definition was: "An arbitrary classification of a space/time region, by a cognitive agent.""""^^xsd:string ;`

give a space like this `" """^^xsd:string`
and update us if still you have a problem with visualization

**Comment by hauschke** [comment]
Thanks, I updated vivo_owl.ttl, there are no more errors. 

Error message is still:
"There is no OWL input under the given IRI(SingleVoc). Please try to load the OWL file directly."

The option to upload seems to be disabled in WebVOWL (which is good). But what can I do to feed WebVOWL?

**Comment by ahemaid** [comment]
I have looked the issue and I have found that you are using owl:imports in "kdsf-vivo-alignment.ttl" file. 
This is not supported till now in visualization, I have just changed it to owl:import just to remove the error.
