### ISSUE TITLE
Only first error is displayed in /validation

### ISSUE THREAD

**Issue by hauschke** [vocol/vocol#96]
I added to errors for testing purposes in a turtle file. The validation shows only one of them:

```
Validation

Error Number: 1
Found in file:./vivo_owl.ttl Error: Syntax error: unexpected "has" on line 66.

Please fix the error(s) in the turtle file(s).

```
If this is a design decision, the message should be fixed to something like:

"Only the first error is shown. Please fix it, before further validation is possible" or something similar. But I would prefer to be able to get a complete list.

**Comment by ahemaid** [comment]
Hi @hauschke

Yes, the message should convey this matter by saying  that we  are showing only the first error of each file. But I am also working towards a parser that  can list all the syntax errors inside turtle file

**Comment by lavdim** [comment]
@ahemaid , is this already implemented?

**Comment by ahemaid** [comment]
Current VoCol version includes RDF-Doctor tool to show more than one syntax errors of the repository.
